version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: attendance_postgres
    restart: always
    ports:
      - "5454:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin321
      POSTGRES_DB: attendance_db
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build: ./Backend
    container_name: attendance_backend
    ports:
      - "3006:3006"
    depends_on:
      - postgres

  employee-attendance:
    build: ./Employee-attendance
    container_name: employee_attendance_ui
    ports:
      - "6028:80"
    depends_on:
      - backend

  hr-attendance:
    build: ./HR-attendance
    container_name: hr_attendance_ui
    ports:
      - "6029:80"
    depends_on:
      - backend

volumes:
  pgdata:
